### ISSUE TITLE
wasm-bindgen v0.2.85 breaks our Playground build

### ISSUE THREAD

**Issue by CMDJojo** [modmark-org/modmark#301]
For some reason, the playground can't build with wasm-bindgen v0.2.85 released one hour ago (previous version v0.2.84 works fine).

The specification in our Cargo.toml says `0.2.84`, which means Cargo is allowed to update it to `0.2.85` (according to SemVer rules). `Cargo.lock` probably prohibits this, so if you remove `Cargo.lock` under playground/web_bindings, it will fail to build with this error message:
```
error[E0433]: failed to resolve: unresolved import
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:67:32
   |
67 |             alloc: &Closure< Fn( usize ) -> *mut u8 >,
   |                                ^ unresolved import

error[E0425]: cannot find function `wasm_bindgen_initialize` in this scope
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:77:22
   |
77 |         let module = wasm_bindgen_initialize( memory, table, &alloc, &free );
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

I think a temporary solution until wasm-bindgen drops a new release is to force the working version 0.2.84.

*Edit*: Filed an issue at https://github.com/rustwasm/wasm-bindgen/issues/3415

**Comment by adelhult** [comment]
The maintainers of `wasm-bindgen` say the problem is caused due to upgrading to `syn` v2. David Tolnay (creator of syn) says that the code that broke in the `stdweb` has produced deprecation warnings for 4 years. Sadly, it looks like `stdweb` been unmaintained since 2020. So it looks like our long term goal should be to stop depending on that crate.

**How do we depend on `stdweb`?** Can we avoid the dependency? Running `cargo tree --target wasm32-unknown-unknown` we can see that the dependency comes from of Wasmer and the `time` crate.
```
       └── wasmer-wasi-types v3.1.1
│           ├── byteorder v1.4.3
│           ├── time v0.2.27
│           │   ├── const_fn v0.4.9 (proc-macro)
│           │   ├── standback v0.2.17
│           │   │   [build-dependencies]
│           │   │   └── version_check v0.9.4
│           │   ├── stdweb v0.4.20
│           │   │   ├── discard v1.0.4
│           │   │   ├── stdweb-derive v0.5.3 (proc-macro)
```
The latest minor release of `time` has removed support for stdweb. [See changelog for 0.3.0](https://github.com/time-rs/time/blob/22ae5793231c5e3df80d9a856da4668915db4bf4/CHANGELOG.md?plain=1#L626).

We are not using the most recent minor version of Wasmer. However, it looks like they still use 0.2 of time. [See Cargo.toml file](https://github.com/wasmerio/wasmer/blob/a32fb739174f43fd126de103832ebf5bfa8ed279/lib/wasi-types/Cargo.toml#L30).

I suspect that the wasmer-js crate will encounter the same issue that we do (since they too [use wasm-bindgen together with wasmer](https://github.com/wasmerio/wasmer-js/blob/80b158341965d6d3203f68ae2be26d5b6858d65b/Cargo.toml#L12)), but they have a lock file commited to Git history so they have not encountered any such issues yet I suspect.

I guess we could open a issue in the Wasmer repo and ask if they have intentions on upgrading to a newer version of the time crate (and if this will cause any problems). For our part it looks like the best option is just to as @CMDJojo  suggested and use 0.2.84 of wasm-bindgen (or commit a lock file for the playground).
